# Generated by Django 6.0.5 on 2026-05-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_counter_counter_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counter',
            options={'ordering': ['created_at']},
        ),
    ]
