# Generated by Django 6.0.5 on 2026-05-29 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_counter_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counter',
            name='counter_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
